### ISSUE TITLE
Don't .RemoveInteger("count")

### ISSUE THREAD

**Issue by bhwithun** [CalvinTheRed/RPGL#27]
[The Code 0.9.0.alpha](https://github.com/CalvinTheRed/RPGL/blob/538863e5273c9c79e2816bc5d81a2b5a050613a8/src/main/java/org/rpgl/core/RPGLEventTemplate.java#L56)

    static void processCost(RPGLEvent event) {
        JsonArray rawCost = event.getCost();
        JsonArray processedCost = new JsonArray();
        for (int i = 0; i < rawCost.size(); i++) {
            JsonObject rawCostElement = rawCost.getJsonObject(i);
            rawCostElement.asMap().putIfAbsent("count", 1);
            rawCostElement.asMap().putIfAbsent("minimum_potency", 1);
            rawCostElement.asMap().putIfAbsent("scale", new ArrayList<>());
            int count = rawCostElement.getInteger("count");                                 <----- fixed it for you
            for (int j = 0; j < count; j++) {
                processedCost.addJsonObject(rawCostElement.deepClone());
            }
        }
        event.setCost(processedCost);
    }

**Comment by CalvinTheRed** [comment]
Upon review, this code was intended to work this way. Rather than leave a `count` field in the JSON to indicate how many of a resource are required by the event cost, the template will automatically reference that field to duplicate the containing resource count-many times in the cost array, none of which are intended to have a `count` field after being copied.

No action needed.
